name       : fwupd
version    : 1.0.5
release    : 1
source     :
    - https://github.com/hughsie/fwupd/archive/1.0.5.tar.gz : 236289aab278fc6611e0a425f7a186895d6755cfdbfd9f182c7bd4bb7fee0324
license    : GPL-2.0
component  : system.boot
summary    : A simple daemon to allow session software to update firmware
description: |
    This project is configured by default to download firmware from the Linux Vendor Firmware Service (LVFS). This service is available to all OEMs and firmware creators who would like to make their firmware available to Linux users.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(colorhug)
    - pkgconfig(fwup)
    - pkgconfig(gnutls)
    - pkgconfig(gusb)
    - pkgconfig(gtk-doc)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libelf)
    - pkgconfig(libsmbios_c)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(sqlite3)
    - dejavu-fonts-ttf
    - docbook-xml
    - gnutls
    - gpgme-devel
    - help2man
    - python-pillow-devel
setup      : |
    %meson_configure -Dman=false
build      : |
    %meson_build
install    : |
    %meson_install
